CREATE DATABASE IF NOT EXISTS itihasyatra_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE itihasyatra_db;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  is_verified TINYINT(1) DEFAULT 0,
  languages VARCHAR(255),
  experience VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS guide_applications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  languages VARCHAR(255),
  experience VARCHAR(255),
  description VARCHAR(1000),
  proof_name VARCHAR(255),
  proof_data LONGBLOB,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  approval_email VARCHAR(255),
  approval_date DATETIME,
  applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_guide_app_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS content (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  creator_id BIGINT,
  type VARCHAR(50) NOT NULL,
  state VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(2000),
  url VARCHAR(2000),
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  created_by VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_content_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trip_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  num_people INT NOT NULL,
  guide_needed TINYINT(1) DEFAULT 0,
  guide_id BIGINT,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_trip_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_trip_guide FOREIGN KEY (guide_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  trip_id BIGINT NOT NULL,
  sender_name VARCHAR(255) NOT NULL,
  message VARCHAR(1000) NOT NULL,
  message_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chat_trip FOREIGN KEY (trip_id) REFERENCES trip_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
